name: BETONA DIZAINS
favicon: null
layout_spectrum: 0.48209
typography_spectrum: 0.80544
title: BETONA DIZAINS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#39424b'
    - '#809399'
    - '#617073'
    - '#1e2225'
    - '#b3c2c5'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
